currency:
  schedule-cron: "0 0 3 * * *"
  api-key: "424082e7f97545ad847d9d86bceabcf5"
  provider-url: "https://api.currencyfreaks.com/v2.0/rates/latest"
  base-currency: "USD"
  scale: 4
  rounding-mode: "HALF_EVEN"
  cache-name: currencyRates

  retry:
    max-attempts: 3
    initial-delay: 1000
    multiplier: 2.0
    max-delay: 5000

  redis:
    ttl-hours: 24
    ttl-currency-rates-hours: 12
  rest:
    connectTimeout: 5
    readTimeout: 5
  kafka:
    request-topic: currency.requests
    reply-topic-prefix: currency.replies.

spring:
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
  application:
    name: currency-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: currency-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
    properties:
      spring.json.trusted.packages: "com.vazant.logix.shared.kafka.dto"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
server:
  port: 8081