spring:
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis

logix:
  currency:
    api-key: "424082e7f97545ad847d9d86bceabcf5"
    provider-url: https://api.currencyfreaks.com/latest
    base-currency: USD
    cron: "0 0 3 * * *"
    retry:
      maxAttempts: 3
      initialDelay: 1000
      multiplier: 2.0
      maxDelay: 5000
    redis:
      time-to-live: 24
      time-to-live-currency-rates: 12
    rest-template:
      connect-timeout: 5
      read-timeout: 5
    rounding-mode: HALF_EVEN
    scale: 4
