spring:
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis

currency:
  redis:
    ttl-hours: 24
    ttl-currency-rates-hours: 12
  provider-url: https://api.currencyfreaks.com/v2.0/rates/latest
  base-currency: USD
  schedule-cron: "0 0 3 * * *"
  api-key: 424082e7f97545ad847d9d86bceabcf5
  scale: 4
  rounding-mode: HALF_EVEN
