server:
  port: 80

spring:
  datasource:
    url: ${ORDERS_DB_URL:jdbc:postgresql://postgres:5432/orders_db}
    username: ${ORDERS_DB_USER:postgres}
    password: ${ORDERS_DB_PASS:postgres}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  kafka:
    bootstrap-servers: ${ORDERS_KAFKA_BOOTSTRAP:localhost:9092}

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

orders:
  data-generator:
    enabled: false
  retry:
    max-attempts: 3
    initial-delay: 1000
    multiplier: 2.0
    max-delay: 5000
  cache:
    ttl-hours: 24
    ttl-currency-rates-hours: 12
  rest:
    connectTimeout: 5
    readTimeout: 5
