server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/orders_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  kafka:
    bootstrap-servers: localhost:29092

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

app:
  data-generator:
    enabled: true

test-container:
  host: localhost
  dbname: orders_db
  username: postgres
  password: postgres
  db-port: 5433

